Develop
MikhailZentsov/java-filmorate pull request #25
Opened 2023-06-11 18:18 UTC by MikhailZentsov

2023-06-12 15:22 UTC, db-exp requested changes

2023-06-12 15:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorageImpl.java
> +                "order by id";
лучше, мне кажется, сортировать по рейтингу

2023-06-12 15:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbReviewStorageImpl.java
> +            assert userId != null;
assert допускается только в тестах - лучше проверить аргумент на уровне контроллера

2023-06-12 15:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static class Builder {
ломбок - аннотация Builder

2023-06-12 15:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public static class Builder {
ломбок - Builder)

2023-06-12 17:51 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                                                           @RequestParam(defaultValue = "10") Integer count) {
Добавил проверку на минимальное значение

2023-06-12 17:58 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +            UserAlreadyExistsException.class,
Исключения объеденены

2023-06-12 18:36 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +            MpaNotFoundException.class,
Исключения объединены

2023-06-12 18:37 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    public static class Builder {
Так исторически сложилось, что lombok используется по минимуму.
Используем сеттеры, геттеры, логирование и конструкторы, так где требуется

Оставил как есть

2023-06-12 18:37 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public static class Builder {
Так исторически сложилось, что lombok используется по минимуму.
Используем сеттеры, геттеры, логирование и конструкторы, так где требуется

Оставил как есть

2023-06-12 18:39 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public static class Builder {
Так исторически сложилось, что lombok используется по минимуму.
Используем сеттеры, геттеры, логирование и конструкторы, так где требуется

Оставил как есть

2023-06-12 18:46 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorageImpl.java
> +                "order by id";
Рейтинг это MPA - рейтинг возрастной доступности к просмотру фильма. Какой смысл по нему сортировать?

Оставил как есть.

2023-06-12 18:51 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/DbFilmServiceImpl.java
> +        return filmStorage.getById(id).orElseThrow(() ->
Ошибка не пробрасывается, Из слоя @Repository возвращается Optional, где подразумевается, что может что-то не найтись для чтения, удаления, изменения.
Опять же, так было со старта этого проекта. Сейчас слишком много всего переписывать.

Оставил как есть.

2023-06-12 19:54 UTC, db-exp requested changes

2023-06-12 19:54 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbDirectorStorageImpl.java
> +        assert director != null;
assert не стоит использовать нигде, кроме тестов

2023-06-12 19:54 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbReviewStorageImpl.java
> +            assert userId != null;
проверка на null - ок, не стоит проверять через assert в реальном коде, только в тестах
На основе твоей ссылки правильно вот так
 if (userId == null)
     throw new ("....");

2023-06-12 19:54 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorageImpl.java
> +                "order by id";
Да, я имел ввиду именно количество лайков, ок

2023-06-12 20:34 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbDirectorStorageImpl.java
> +        assert director != null;
Везде в библиотеках используется именно эта проверка, так как она как раз отключаемая. Хорошо убрал.

2023-06-13 08:28 UTC, danyyyaa approved these changes

2023-06-13 08:57 UTC, merged