add-marks
MikhailZentsov/java-filmorate pull request #29
Opened 2023-06-17 18:58 UTC by MikhailZentsov

2023-06-17 19:47 UTC, GordPavel requested changes
По общей архитектуре выглядит ок. Но есть несколько технических комментов

2023-06-17 19:47 UTC, GordPavel commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/DbFilmServiceImpl.java
> +        log.info("Получение популярных фильмов с отбором");
log.trace

2023-06-17 19:47 UTC, GordPavel commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/DbFilmServiceImpl.java
> +        userStorage.getById(userId).orElseThrow(() ->
Не надо 404. Не найдёшь по userId – верни пустой список

2023-06-17 19:47 UTC, GordPavel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbEventStorageImpl.java
> +                "order by event_timestamp ";
А зачем вам обязательная сортировка, если она не указана в сигнатуре

2023-06-17 19:47 UTC, GordPavel commented on src/main/java/ru/yandex/practicum/filmorate/storage/trigger/CalcRateTrigger.java
> +public class CalcRateTrigger implements Trigger {
А что за зависимость от h2 интерфейса в проде?

2023-06-17 19:47 UTC, GordPavel commented on src/main/java/ru/yandex/practicum/filmorate/storage/trigger/CalcRateTrigger.java
> +        try (PreparedStatement stmt = connection.prepareStatement(
У вас будет создаваться prepared statement каждый раз при вызове метода? Может перенести в init и потом вызывать? Или почему вообще тут именно prepared statement?

2023-06-17 19:47 UTC, GordPavel commented on src/main/resources/sql/schema.sql
> +call "ru.yandex.practicum.filmorate.storage.trigger.CalcRateTrigger";
Объясните плз, как вы на БД вызываете java код?

2023-06-18 14:52 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/trigger/CalcRateTrigger.java
> +public class CalcRateTrigger implements Trigger {
В H2 нет поддержки хранимых процедур. Хотел изучить этот механизм.
Перепишу на вызов метода, как евенты

2023-06-18 14:54 UTC, MikhailZentsov commented on src/main/resources/sql/schema.sql
> +call "ru.yandex.practicum.filmorate.storage.trigger.CalcRateTrigger";
Это особенность H2, по сути тут надо вызывать хранимую процедуру. Но H2 не может в хранимые и вместо этого вызывает триггеры классы

2023-06-18 14:55 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/DbFilmServiceImpl.java
> +        userStorage.getById(userId).orElseThrow(() ->
Ок, переделаю.

2023-06-18 14:55 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/DbFilmServiceImpl.java
> +        log.info("Получение популярных фильмов с отбором");
Переделаю, разумно

2023-06-18 15:03 UTC, MikhailZentsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbEventStorageImpl.java
> +                "order by event_timestamp ";
В тестах постмана был порядок изначально. Ведь SQL не гарантирует порядок по добавлению записей, если не указан явно через order by

2023-06-19 07:31 UTC, GordPavel commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbEventStorageImpl.java
> +                "order by event_timestamp ";
понял

2023-06-19 10:13 UTC, GordPavel commented on src/main/resources/sql/schema.sql
> +call "ru.yandex.practicum.filmorate.storage.trigger.CalcRateTrigger";
я бы не закладывался в продовом коде на H2 сущности, потому как это чисто БД для тестов. Иногда применяется в проде, но это супер интересный случай должен быть

2023-07-26 10:52 UTC, merged